server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpabook?serverTimezone=Asia/Seoul
    username: jpa
    password: jpa


jpa:
  hibernate:
    ddl-auto: create  # ??? ?? ??
  show-sql: true      # SQL ?? ??
  properties:
    hibernate:
      format_sql: true  # SQL pretty print